service: aws-billing-notifier
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1
  deploymentBucket: serverless-upload-us-east-1
  versionFunctions: false
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "cloudwatch:GetMetricStatistics"
          Resource: "*"

functions:
  main:
    handler: handler
    description: Post aws billing info to slack
    timeout: 60
    memorySize: 1024
    environment:
      SLACK_WEBHOOK_URL: "${ssm:/slack/webhook/dev}"
    events:
      - schedule: cron(0 0 * * ? *)

resources:
  Description: Post aws billing info to slack
  Resources:
    IamRoleLambdaExecution:
      Type: AWS::IAM::Role
      Properties:
        RoleName: "${self:service}"
    MainLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: 7
